language: php

php:
  - 7.0
  - 7.1

env:
  - COMPOSER_FLAGS=--prefer-lowest
  - COMPOSER_FLAGS=

before_script:
  - composer update --no-interaction --no-suggest --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
